@base = http://localhost:4000/api/commodity
@base2 = http://localhost:4000/api/events
@base3 = http://localhost:4000/api/members
@base4 = http://localhost:4000/api/testimonials
@base5 = http://localhost:4000/api/introduce
@base6 = http://localhost:4000/api/services
@base7 = http://localhost:4000/api/banner



# @name getAllCommodity

GET {{base}}

###

# @name getEvents
GET {{base2}}

###

# @name getMember
GET {{base3}}

###

# @name getTestimonials
GET {{base4}}

###

# @name getIntroduce
GET {{base5}}

###

# @name getServices
GET {{base6}}

###

# @name getBanner
GET {{base7}}

###

# @name addNewCommodity
POST {{base}}
Content-Type: application/json

{
  "img": "images/56.png",
  "name": "Red Bull Energy Drink (250 Ml)",
  "price": 7,
  "realPrice": 9,
  "positon": "offer"
}

###

# @name addNewEvent
POST {{base2}}
Content-Type: application/json

{
  "Date": "21-july-2016",
  "img": "images/19.jpg",
  "title": "MAXIME PLACEAT FACERE POSSIMUS",
  "user": "Admin",
  "description": "Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est."
}

###

# @name updateCommodity
PATCH {{base}}/16
Content-Type: application/json

{
  "img": "images/16.png"
}

###

# @name updateEvent
PATCH {{base2}}/2
Content-Type: application/json

{
  "date": "July 21, 2016 15:30:00"
}

###

# @name DeleteCommodity
DELETE {{base}}/17

###

# @name filterCommodity
GET {{base}}?position=gift

###

# @name paginate
GET {{base}}?_page=2&_limit=4

###

# @name sort
GET {{base}}?_sort=price&_order=asc

###

# @name slice
GET {{base}}?_start=10&_end=20

###

# @name addNewMember
POST {{base3}}
Content-Type: application/json

{
  "img": "images/35.jpg",
  "name": "LAURA LEE",
  "position": "CEO",
  "facebook": "",
  "twitter": "",
  "google": ""
}

###

# @name addNewTestimonials
POST {{base4}}
Content-Type: application/json

{
  "feedback": "Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.",
  "user": "ROCKSON DOE",
  "position": "CUSTOMER"
}

###

# @name addNewIntroduce
POST {{base5}}
Content-Type: application/json

{
  "img": "/images/30.jpg",
  "title": "Frozen Soybean",
  "li": ["Dolorem Eum Fugiat Voluptas", "Ut Aliquid Ex Ea Commodi", "Magnam Aliquam Quaerat"]
}

###

# @name addNewServices
POST {{base6}}
Content-Type: application/json

{
  "followers": 89147,
  "savings": 54598,
  "support": 83983,
  "popularity": 45894
}

###

# @name addNewBanner
POST  {{base7}}
Content-Type: application/json

{
  "id": 8,
  "img": "/images/28.jpg"
}